export type ImageKey = 'islands' | 'villas' | 'yacht' | 'desert';

export interface Journey {
  id: string;
  name: string;
  destination: string;
  region: string;
  duration: string;
  bestTime: string;
  overview: string;
  imageKey: ImageKey;
  readonly places: readonly string[];
  readonly restaurants: readonly string[];
  readonly experiences: readonly string[];
}

export const JOURNEYS: readonly Journey[] = [
  {
    id: 'maldives',
    name: 'Maldives Escape',
    destination: 'Maldives',
    region: 'Indian Ocean',
    duration: '7 Days',
    bestTime: 'Nov – Apr',
    overview: 'Drift between coral atolls and overwater villas in the most pristine archipelago on earth. Crystalline lagoons, powder-white sandbanks, and marine life that exists nowhere else.',
    imageKey: 'islands',
    places: ['Baa Atoll Biosphere Reserve', 'Veligandu Island', 'Banana Reef', 'Fulhadhoo Island', 'Sun Island'],
    restaurants: ['Sea of Stars Beach', 'Leaf Restaurant', 'Azur Ocean Terrace', 'Lagoon Dining'],
    experiences: ['Snorkelling at Coral Gardens', 'Sunrise Paddleboarding', 'Sandbank Picnic', 'Island Hopping', 'Bioluminescent Night Walk'],
  },
  {
    id: 'santorini',
    name: 'Santorini Retreat',
    destination: 'Santorini',
    region: 'Cyclades, Greece',
    duration: '5 Days',
    bestTime: 'May – Oct',
    overview: 'Perched on volcanic clifftops above the ancient caldera, Santorini\'s iconic whitewashed villages and infinite sea views make it the Aegean\'s most celebrated island.',
    imageKey: 'villas',
    places: ['Oia Village', 'Ancient Akrotiri', 'Red Beach', 'Perissa Black Sand Beach', 'Fira Cathedral'],
    restaurants: ['Ambrosia Caldera', 'Kastro Oia', 'Selene', 'Metaxi Mas Exo Gonia'],
    experiences: ['Caldera Sunset Cruise', 'Volcanic Hot Springs', 'Wine Tasting at Santo Wines', 'Photography Walk through Oia', 'Cooking Class with Local Chefs'],
  },
  {
    id: 'dubai',
    name: 'Dubai Edition',
    destination: 'Dubai',
    region: 'UAE',
    duration: '5 Days',
    bestTime: 'Oct – Apr',
    overview: 'A city that rewrites the limits of ambition at every turn. From world-record towers and golden desert dunes to art districts and fragrant souk labyrinths.',
    imageKey: 'desert',
    places: ['Burj Khalifa At the Top', 'Al Fahidi Historical District', 'Dubai Frame', 'Palm Jumeirah', 'Spice Souk'],
    restaurants: ['Nobu Atlantis', 'Zuma DIFC', 'Tresind Studio', 'Pierchic'],
    experiences: ['Desert Dune Safari at Sunrise', 'Gold Souk Discovery', 'Dhow Dinner Cruise', 'Alserkal Avenue Art Walk'],
  },
  {
    id: 'bora-bora',
    name: 'Bora Bora Sanctuary',
    destination: 'Bora Bora',
    region: 'French Polynesia',
    duration: '6 Days',
    bestTime: 'May – Oct',
    overview: 'Mount Otemanu rises above an impossibly vivid turquoise lagoon. One of the last places on earth where seclusion and natural grandeur exist in perfect unison.',
    imageKey: 'islands',
    places: ['Mount Otemanu', 'Matira Beach', 'Coral Gardens', 'Motu Tapu', 'Bloody Mary\'s Island'],
    restaurants: ['Restaurant Fare Hoa', 'Bloody Mary\'s', 'Aloe Restaurant', 'La Villa Mahana'],
    experiences: ['Lagoon Kayaking', 'Shark & Ray Snorkelling', 'Pearl Farm Visit', 'Sunset Helicopter Tour', 'Sacred Sites Walk'],
  },
  {
    id: 'seychelles',
    name: 'Seychelles Escape',
    destination: 'Seychelles',
    region: 'Indian Ocean',
    duration: '7 Days',
    bestTime: 'Apr – May, Oct – Nov',
    overview: 'Ancient granite boulders frame beaches that seem designed by a painter\'s imagination. The Seychelles remain one of the last truly wild, luxurious island retreats on the planet.',
    imageKey: 'islands',
    places: ['Vallée de Mai Nature Reserve', 'Anse Lazio', 'Coco Island', 'La Digue', 'Aldabra Atoll'],
    restaurants: ['Marie Antoinette', 'Boat House', 'La Plage', 'Chez Jules'],
    experiences: ['Giant Tortoise Sanctuary Visit', 'Coco de Mer Forest Walk', 'Snorkelling Marine Park', 'Traditional Creole Cooking', 'Island Hopping'],
  },
  {
    id: 'bali',
    name: 'Bali Immersion',
    destination: 'Bali',
    region: 'Indonesia',
    duration: '8 Days',
    bestTime: 'Apr – Oct',
    overview: 'An island where spirituality, art, and volcanic landscapes merge. From rice terrace valleys to oceanfront temples, Bali rewards the curious and the contemplative.',
    imageKey: 'villas',
    places: ['Tegallalang Rice Terraces', 'Tanah Lot Temple', 'Ubud Sacred Monkey Forest', 'Besakih Mother Temple', 'Nusa Penida Cliffs'],
    restaurants: ['Locavore Ubud', 'Mozaic Restaurant', 'Swept Away at COMO Shambhala', 'Merah Putih'],
    experiences: ['Dawn Meditation at Campuhan Ridge', 'Silver Jewellery Workshop', 'Jatiluwih Cycling Tour', 'Traditional Kecak Dance', 'Sunrise Volcano Trek'],
  },
  {
    id: 'swiss-alps',
    name: 'Swiss Alps Winter',
    destination: 'Swiss Alps',
    region: 'Switzerland',
    duration: '6 Days',
    bestTime: 'Dec – Mar',
    overview: 'Towering peaks, crystalline alpine air, and centuries of precision craftsmanship. The Swiss Alps define the premium mountain experience in every season.',
    imageKey: 'desert',
    places: ['Jungfraujoch — Top of Europe', 'Grindelwald Village', 'Matterhorn Glacier Paradise', 'Aletsch Glacier', 'Lucerne Chapel Bridge'],
    restaurants: ['Restaurant Chesery Gstaad', 'Il Tartufo Verbier', 'Altitude Restaurant Zermatt', 'La Vache Crans-Montana'],
    experiences: ['Off-Piste Ski Touring', 'Glacier Hiking', 'Chocolate Atelier Visit', 'Alpine Wellness Spa', 'Fondue in a Mountain Hut'],
  },
  {
    id: 'monaco',
    name: 'Monaco Grand Tour',
    destination: 'Monaco',
    region: 'French Riviera',
    duration: '4 Days',
    bestTime: 'May – Sep',
    overview: 'The Principality that redefined glamour. Every thoroughfare is a stage, from the legendary casino to the cliff-hugging Grand Prix circuit.',
    imageKey: 'yacht',
    places: ['Casino de Monte-Carlo', 'Prince\'s Palace & Changing of the Guard', 'Oceanographic Museum', 'Jardin Exotique', 'Old Town Rock'],
    restaurants: ['Le Louis XV – Alain Ducasse', 'Joël Robuchon Restaurant', 'Blue Bay Monte-Carlo', 'Maya Bay'],
    experiences: ['Port Hercule Yacht Walk', 'Grand Prix Circuit Walk', 'Casino Royale Evening', 'Perfume Atelier Grasse Day Trip', 'Monaco Historic Drive'],
  },
  {
    id: 'amalfi-coast',
    name: 'Amalfi Coast Journey',
    destination: 'Amalfi Coast',
    region: 'Campania, Italy',
    duration: '6 Days',
    bestTime: 'May – Sep',
    overview: 'A UNESCO World Heritage coastline of pastel villages, lemon groves, and cerulean sea. The Amalfi Drive remains one of the world\'s most scenic roads.',
    imageKey: 'yacht',
    places: ['Positano Village', 'Ravello Gardens', 'Amalfi Cathedral', 'Emerald Grotto', 'Furore Fjord'],
    restaurants: ['Don Alfonso 1890', 'Ristorante Max Positano', 'La Serra Ravello', 'Il Pirata D\'Amalfi'],
    experiences: ['Path of the Gods Hiking Trail', 'Limoncello Distillery Visit', 'Coastal Sailing Day', 'Pompeii Archaeological Walk', 'Ceramics Workshop Vietri'],
  },
  {
    id: 'tokyo',
    name: 'Tokyo Discovery',
    destination: 'Tokyo',
    region: 'Kantō, Japan',
    duration: '7 Days',
    bestTime: 'Mar – May, Sep – Nov',
    overview: 'The city that moves at the speed of the future without abandoning its ancient soul. From Michelin-star dining to serene temple gardens, Tokyo contains multitudes.',
    imageKey: 'villas',
    places: ['Senso-ji Temple Asakusa', 'TeamLab Borderless', 'Tsukiji Outer Market', 'Shinjuku Gyoen Garden', 'Roppongi Hills'],
    restaurants: ['Sukiyabashi Jiro Honten', 'Ryugin Nishiazabu', 'Ishikawa Kagurazaka', 'Narisawa Minami-Aoyama'],
    experiences: ['Dawn Tuna Auction Observation', 'Traditional Tea Ceremony', 'Kabuki Theatre Matinée', 'Shibuya Crossing at Night', 'Woodblock Print Workshop'],
  },
  {
    id: 'kyoto',
    name: 'Kyoto Cultural Immersion',
    destination: 'Kyoto',
    region: 'Kansai, Japan',
    duration: '5 Days',
    bestTime: 'Mar – Apr, Oct – Nov',
    overview: 'Japan\'s ancient capital holds more UNESCO World Heritage sites than almost any city on earth. Where Zen philosophy becomes visible in garden, temple, and alley.',
    imageKey: 'villas',
    places: ['Fushimi Inari-Taisha Shrine', 'Arashiyama Bamboo Grove', 'Kinkaku-ji Golden Pavilion', 'Philosopher\'s Path', 'Nishiki Market'],
    restaurants: ['Kikunoi Honten', 'Nakamura Nakagyo', 'Mizai Gion', 'Kichisen'],
    experiences: ['Dawn Walk at Fushimi Inari', 'Matcha Ceremony at Urasenke', 'Geisha District Evening Walk', 'Ikebana Flower Arrangement', 'Kodo Incense Ceremony'],
  },
  {
    id: 'iceland',
    name: 'Iceland Wild',
    destination: 'Iceland',
    region: 'North Atlantic',
    duration: '7 Days',
    bestTime: 'Jun – Aug · Dec – Feb',
    overview: 'Where volcanic fire meets ancient ice. Iceland offers landscapes that challenge every expectation — geysers, glaciers, aurora borealis, and empty roads to infinity.',
    imageKey: 'desert',
    places: ['Blue Lagoon Geothermal Spa', 'Gullfoss Waterfall', 'Geysir Geothermal Area', 'Skógafoss Falls', 'Jökulsárlón Glacier Lagoon'],
    restaurants: ['Dill Restaurant Reykjavík', 'Matur og Drykkur', 'Grillið Sky Restaurant', 'Fiskfélagið Fish Company'],
    experiences: ['Northern Lights Photography', 'Glacier Hiking Vatnajökull', 'Midnight Sun Walk', 'Whale Watching', 'Puffin Colony Visit'],
  },
  {
    id: 'french-riviera',
    name: 'French Riviera',
    destination: 'Côte d\'Azur',
    region: 'Provence, France',
    duration: '6 Days',
    bestTime: 'May – Sep',
    overview: 'Sunlight over the Mediterranean, rosé on sun-bleached terraces, and the effortless glamour that only the Riviera can produce. From Nice to Antibes, every stop is iconic.',
    imageKey: 'yacht',
    places: ['Old Town Nice', 'Cap Ferrat Peninsula', 'Antibes Ramparts', 'Eze Village', 'Cannes La Croisette'],
    restaurants: ['La Petite Maison Nice', 'Chèvre d\'Or Eze', 'Le Mas Candille Mougins', 'Christian Etienne Avignon'],
    experiences: ['Yacht Day along the Coast', 'Lavender Fields Grasse Walk', 'Picasso Museum Antibes', 'Morning Fish Market Nice', 'Scenic Drive Grande Corniche'],
  },
  {
    id: 'tuscany',
    name: 'Tuscany Harvest',
    destination: 'Tuscany',
    region: 'Central Italy',
    duration: '7 Days',
    bestTime: 'Apr – Jun, Sep – Oct',
    overview: 'Rolling hills of cypresses, Renaissance hilltowns, and the terroir that gives the world Brunello and Chianti. Tuscany is the art of living made landscape.',
    imageKey: 'villas',
    places: ['Siena Medieval Centre', 'Val d\'Orcia Valley', 'San Gimignano Towers', 'Volterra', 'Montalcino Castle'],
    restaurants: ['Osteria di Passignano', 'Buca Mario Firenze', 'La Bottega del 30', 'Il Falconiere Cortona'],
    experiences: ['Truffle Hunting with Dogs', 'Sunset at Podere Belvedere', 'Chianti Classico Cycling Route', 'Leather Workshop Firenze', 'Pecorino Cheese Tasting'],
  },
  {
    id: 'marrakech',
    name: 'Marrakech Medina',
    destination: 'Marrakech',
    region: 'Morocco',
    duration: '5 Days',
    bestTime: 'Mar – May, Oct – Nov',
    overview: 'Ochre walls, scented souks, and riads with courtyard fountains that blur the boundary between dream and reality. Marrakech engages every sense simultaneously.',
    imageKey: 'desert',
    places: ['Djemaa el-Fna Square', 'Saadian Tombs', 'Bahia Palace', 'Jardin Majorelle', 'Medina Souks'],
    restaurants: ['Le Jardin Marrakech', 'Nomad Derb Aarjane', 'Dar Moha', 'La Maison Arabe'],
    experiences: ['Souk Navigation with Local Guide', 'Hammam Ritual', 'Erg Chebbi Camel Sunrise', 'Cooking Class in a Riad', 'Atlas Mountains Day Walk'],
  },
  {
    id: 'cappadocia',
    name: 'Cappadocia Sky',
    destination: 'Cappadocia',
    region: 'Anatolia, Turkey',
    duration: '4 Days',
    bestTime: 'Apr – Jun, Sep – Nov',
    overview: 'A dreamscape of volcanic rock sculpted over millennia into spires, valleys, and cave dwellings. At dawn, hundreds of hot air balloons fill the sky — one of travel\'s most transcendent sights.',
    imageKey: 'desert',
    places: ['Göreme Open-Air Museum', 'Uçhisar Castle', 'Rose Valley Hiking Trail', 'Derinkuyu Underground City', 'Pigeon Valley'],
    restaurants: ['Seten Restaurant', 'Dibek Göreme', 'Peri Restaurant', 'Topdeck Cave Restaurant'],
    experiences: ['Dawn Hot Air Balloon Flight', 'Cave Church Fresco Walk', 'Pottery Workshop Avanos', 'Whirling Dervish Ceremony', 'Underground City Exploration'],
  },
  {
    id: 'zanzibar',
    name: 'Zanzibar Shores',
    destination: 'Zanzibar',
    region: 'Tanzania',
    duration: '6 Days',
    bestTime: 'Jun – Oct',
    overview: 'Spice islands fringed by Indian Ocean waters of impossible turquoise. Stone Town\'s labyrinthine alleys tell centuries of Swahili, Arab, and Portuguese history.',
    imageKey: 'islands',
    places: ['Stone Town UNESCO Old City', 'Jozani Chwaka Bay Forest', 'Nungwi Beach', 'Mnemba Island', 'Prison Island Tortoise Sanctuary'],
    restaurants: ['The Rock Restaurant', 'The Swahili House', 'Emerson Spice Rooftop', 'Forodhani Gardens Night Market'],
    experiences: ['Spice Plantation Tour', 'Sunset Dhow Cruise', 'Swimming with Dolphins', 'Blue Safari Island', 'Stone Town Night Walk'],
  },
  {
    id: 'singapore',
    name: 'Singapore Edit',
    destination: 'Singapore',
    region: 'Southeast Asia',
    duration: '4 Days',
    bestTime: 'Feb – Apr',
    overview: 'An island city-state that distills the future of urban living. Immaculate parks, world-class dining, and multilayered cultural districts reward every type of explorer.',
    imageKey: 'villas',
    places: ['Gardens by the Bay Supertrees', 'Marina Bay Sands Skypark', 'Chinatown Heritage Centre', 'Kampong Glam Arab Quarter', 'Botanic Gardens UNESCO'],
    restaurants: ['Odette National Gallery', 'Les Amis Orchard', 'Burnt Ends Teck Lim', 'Zén Bukit Pasoh'],
    experiences: ['Supertree Grove Light Show', 'Hawker Centre Food Walk', 'Singapore River History Walk', 'Sentosa Island Day', 'Night Safari'],
  },
  {
    id: 'lake-como',
    name: 'Lake Como Idyll',
    destination: 'Lake Como',
    region: 'Lombardy, Italy',
    duration: '5 Days',
    bestTime: 'Apr – Jun, Sep – Oct',
    overview: 'Lombardy\'s glacial lake has been the retreat of European nobility and artists for centuries. Villa gardens, ferry crossings, and Dolomite reflections create an atmosphere unlike anywhere else.',
    imageKey: 'yacht',
    places: ['Bellagio Village', 'Villa del Balbianello Gardens', 'Varenna Old Town', 'Como Cathedral', 'Villa Carlotta Botanical Gardens'],
    restaurants: ['Ristorante La Punta Bellagio', 'Berton al Lago', 'Al Gatto Nero Cernobbio', 'Il Sereno Lago di Como'],
    experiences: ['Lake Ferry Island Hopping', 'Villa Garden Private Tour', 'Kayaking at Dawn', 'Silk Factory Visit Como Town', 'Hiking Monte Bregagno'],
  },
  {
    id: 'patagonia',
    name: 'Patagonia Expedition',
    destination: 'Patagonia',
    region: 'Chile & Argentina',
    duration: '10 Days',
    bestTime: 'Nov – Mar',
    overview: 'The end of the world, rendered magnificent. Patagonia\'s granite towers, ancient glaciers, and wild pampas represent the last great wilderness — untouched, untamed, unforgettable.',
    imageKey: 'desert',
    places: ['Torres del Paine National Park', 'Perito Moreno Glacier', 'Fitz Roy Massif', 'Puerto Natales', 'Tierra del Fuego'],
    restaurants: ['Eolo Lodge Dining Room', 'La Mesita Grande Torres del Paine', 'Martin Fierro Puerto Natales', 'El Calafate Parrilla'],
    experiences: ['W Trek Multi-Day Hike', 'Glacier Ice Walk', 'Condor Observation', 'Gaucho Estancia Day', 'Stargazing in the Pampa'],
  },
];
