export type ImageKey = 'islands' | 'villas' | 'yacht' | 'desert' | 'mountain' | 'city' | 'temple' | 'bali' | 'seychelles' | 'zanzibar' | 'lakecomo' | 'alps';
export type BudgetLevel = '$' | '$$' | '$$$' | '$$$$';

export interface ItineraryDay {
  day: number;
  activities: readonly string[];
}

export interface Journey {
  id: string;
  name: string;
  destination: string;
  region: string;
  duration: string;
  bestTime: string;
  overview: string;
  imageKey: ImageKey;
  budget: BudgetLevel;
  dailyBudget: string;
  /** Per-journey traveler rating (1–5) */
  rating: number;
  /** Links to a Creator in constants/creators.ts */
  creatorId: string;
  /** Platform save count (used for social proof on cards) */
  savedCount: number;
  itinerary: readonly ItineraryDay[];
  readonly places: readonly string[];
  readonly restaurants: readonly string[];
  readonly experiences: readonly string[];
}

export const JOURNEYS: readonly Journey[] = [
  {
    id: 'maldives',
    creatorId: 'james-hartley',
    savedCount: 1840,
    rating: 4.9,
    name: 'Maldives Escape',
    destination: 'Maldives',
    region: 'Indian Ocean',
    duration: '7 Days',
    bestTime: 'Nov – Apr',
    overview: 'Drift between coral atolls and overwater villas in the most pristine archipelago on earth. Crystalline lagoons, powder-white sandbanks, and marine life that exists nowhere else.',
    imageKey: 'islands',
    budget: '$$$$',
    dailyBudget: '$400–800/day',
    itinerary: [
      { day: 1, activities: ['Seaplane arrival to private atoll', 'Welcome sunset cocktail on the sandbank', 'Overwater villa check-in'] },
      { day: 2, activities: ['Sunrise snorkelling at Coral Gardens', 'Paddleboard across the lagoon', 'Underwater restaurant dinner'] },
      { day: 3, activities: ['Baa Atoll manta ray encounter', 'Island picnic on uninhabited sandbank', 'Bioluminescent beach walk at dusk'] },
      { day: 4, activities: ['Sunrise paddleboarding session', 'Reef shark dive', 'Spa treatment over the lagoon'] },
      { day: 5, activities: ['Dolphin spotting boat excursion', 'Fulhadhoo Island village visit', 'Beachside dining under stars'] },
      { day: 6, activities: ['Deep-sea fishing at dawn', 'Cooking class: Maldivian cuisine', 'Glass-bottom kayak at sunset'] },
      { day: 7, activities: ['Final reef snorkel', 'Seaplane farewell over the atolls', 'Departure'] },
    ],
    places: ['Baa Atoll Biosphere Reserve', 'Veligandu Island', 'Banana Reef', 'Fulhadhoo Island', 'Sun Island'],
    restaurants: ['Sea of Stars Beach', 'Leaf Restaurant', 'Azur Ocean Terrace', 'Lagoon Dining'],
    experiences: ['Snorkelling at Coral Gardens', 'Sunrise Paddleboarding', 'Sandbank Picnic', 'Island Hopping', 'Bioluminescent Night Walk'],
  },
  {
    id: 'santorini',
    creatorId: 'marco-vitale',
    savedCount: 2310,
    rating: 4.8,
    name: 'Santorini Retreat',
    destination: 'Santorini',
    region: 'Cyclades, Greece',
    duration: '5 Days',
    bestTime: 'May – Oct',
    overview: 'Perched on volcanic clifftops above the ancient caldera, Santorini\'s iconic whitewashed villages and infinite sea views make it the Aegean\'s most celebrated island.',
    imageKey: 'villas',
    budget: '$$$',
    dailyBudget: '$180–280/day',
    itinerary: [
      { day: 1, activities: ['Arrive Fira, cliff-walk to Firostefani', 'Caldera viewpoint sunset aperitivo', 'Dinner at Ambrosia Caldera'] },
      { day: 2, activities: ['Oia village morning walk', 'Photography at the blue domes', 'Kastro wine bar at dusk'] },
      { day: 3, activities: ['Ancient Akrotiri archaeological site', 'Red Beach swim', 'Cooking class: local mezze'] },
      { day: 4, activities: ['Caldera Sunset Cruise', 'Volcanic hot springs', 'Wine tasting at Santo Wines'] },
      { day: 5, activities: ['Perissa Black Sand Beach morning', 'Fira Cathedral', 'Farewell caldera sunset'] },
    ],
    places: ['Oia Village', 'Ancient Akrotiri', 'Red Beach', 'Perissa Black Sand Beach', 'Fira Cathedral'],
    restaurants: ['Ambrosia Caldera', 'Kastro Oia', 'Selene', 'Metaxi Mas Exo Gonia'],
    experiences: ['Caldera Sunset Cruise', 'Volcanic Hot Springs', 'Wine Tasting at Santo Wines', 'Photography Walk through Oia', 'Cooking Class with Local Chefs'],
  },
  {
    id: 'dubai',
    creatorId: 'nadia-al-rashid',
    savedCount: 1620,
    rating: 4.7,
    name: 'Dubai Edition',
    destination: 'Dubai',
    region: 'UAE',
    duration: '5 Days',
    bestTime: 'Oct – Apr',
    overview: 'A city that rewrites the limits of ambition at every turn. From world-record towers and golden desert dunes to art districts and fragrant souk labyrinths.',
    imageKey: 'desert',
    budget: '$$$',
    dailyBudget: '$200–350/day',
    itinerary: [
      { day: 1, activities: ['Burj Khalifa At the Top at sunset', 'Dubai Mall fountains show', 'Dinner at Zuma DIFC'] },
      { day: 2, activities: ['Desert dune safari at sunrise', 'Falconry demonstration', 'Bedouin camp dinner under stars'] },
      { day: 3, activities: ['Al Fahidi Historical District walk', 'Spice Souk and Gold Souk', 'Dhow dinner cruise on the Creek'] },
      { day: 4, activities: ['Palm Jumeirah promenade', 'Atlantis waterpark', 'Pierchic overwater dinner'] },
      { day: 5, activities: ['Dubai Frame panoramic visit', 'Alserkal Avenue contemporary art', 'Departure'] },
    ],
    places: ['Burj Khalifa At the Top', 'Al Fahidi Historical District', 'Dubai Frame', 'Palm Jumeirah', 'Spice Souk'],
    restaurants: ['Nobu Atlantis', 'Zuma DIFC', 'Tresind Studio', 'Pierchic'],
    experiences: ['Desert Dune Safari at Sunrise', 'Gold Souk Discovery', 'Dhow Dinner Cruise', 'Alserkal Avenue Art Walk'],
  },
  {
    id: 'bora-bora',
    creatorId: 'james-hartley',
    savedCount: 2180,
    rating: 4.9,
    name: 'Bora Bora Sanctuary',
    destination: 'Bora Bora',
    region: 'French Polynesia',
    duration: '6 Days',
    bestTime: 'May – Oct',
    overview: 'Mount Otemanu rises above an impossibly vivid turquoise lagoon. One of the last places on earth where seclusion and natural grandeur exist in perfect unison.',
    imageKey: 'islands',
    budget: '$$$$',
    dailyBudget: '$500–900/day',
    itinerary: [
      { day: 1, activities: ['Arrival by boat transfer to overwater bungalow', 'Lagoon snorkel from private dock', 'Sunset champagne on the terrace'] },
      { day: 2, activities: ['Mount Otemanu guided hike at dawn', 'Matira Beach afternoon', 'Dinner at La Villa Mahana'] },
      { day: 3, activities: ['Shark & Ray snorkelling tour', 'Coral Gardens kayaking', 'Pearl farm visit'] },
      { day: 4, activities: ['Motu Tapu private island picnic', 'Sunset helicopter tour over the lagoon', 'Aloe Restaurant dinner'] },
      { day: 5, activities: ['Sacred sites walking tour', 'Traditional outrigger canoe paddle', 'Stargazing from the bungalow'] },
      { day: 6, activities: ['Final dawn snorkel', 'Farewell boat transfer', 'Departure'] },
    ],
    places: ['Mount Otemanu', 'Matira Beach', 'Coral Gardens', 'Motu Tapu', 'Bloody Mary\'s Island'],
    restaurants: ['Restaurant Fare Hoa', 'Bloody Mary\'s', 'Aloe Restaurant', 'La Villa Mahana'],
    experiences: ['Lagoon Kayaking', 'Shark & Ray Snorkelling', 'Pearl Farm Visit', 'Sunset Helicopter Tour', 'Sacred Sites Walk'],
  },
  {
    id: 'seychelles',
    creatorId: 'amara-osei',
    savedCount: 1490,
    rating: 4.8,
    name: 'Seychelles Escape',
    destination: 'Seychelles',
    region: 'Indian Ocean',
    duration: '7 Days',
    bestTime: 'Apr – May, Oct – Nov',
    overview: 'Ancient granite boulders frame beaches that seem designed by a painter\'s imagination. The Seychelles remain one of the last truly wild, luxurious island retreats on the planet.',
    imageKey: 'seychelles',
    budget: '$$$$',
    dailyBudget: '$400–700/day',
    itinerary: [
      { day: 1, activities: ['Arrive Mahé, transfer to Praslin', 'Anse Lazio beach sunset swim', 'Creole welcome dinner'] },
      { day: 2, activities: ['Vallée de Mai UNESCO forest walk', 'Coco de Mer palm grove', 'Boat to La Digue'] },
      { day: 3, activities: ['La Digue cycling tour', 'Anse Source d\'Argent granitic beach', 'Snorkelling coral garden'] },
      { day: 4, activities: ['Giant tortoise sanctuary visit', 'Creole cooking class', 'Sunset boat cruise'] },
      { day: 5, activities: ['Aldabra Atoll day trip by boat', 'Marine park snorkelling', 'Beachside Chez Jules dinner'] },
      { day: 6, activities: ['Island hopping: Silhouette Island', 'Traditional Creole market', 'La Plage farewell dinner'] },
      { day: 7, activities: ['Boat House morning brunch', 'Final beach walk', 'Departure from Mahé'] },
    ],
    places: ['Vallée de Mai Nature Reserve', 'Anse Lazio', 'Coco Island', 'La Digue', 'Aldabra Atoll'],
    restaurants: ['Marie Antoinette', 'Boat House', 'La Plage', 'Chez Jules'],
    experiences: ['Giant Tortoise Sanctuary Visit', 'Coco de Mer Forest Walk', 'Snorkelling Marine Park', 'Traditional Creole Cooking', 'Island Hopping'],
  },
  {
    id: 'bali',
    creatorId: 'amara-osei',
    savedCount: 3840,
    rating: 4.9,
    name: 'Bali Immersion',
    destination: 'Bali',
    region: 'Indonesia',
    duration: '8 Days',
    bestTime: 'Apr – Oct',
    overview: 'An island where spirituality, art, and volcanic landscapes merge. From rice terrace valleys to oceanfront temples, Bali rewards the curious and the contemplative.',
    imageKey: 'bali',
    budget: '$$',
    dailyBudget: '$60–100/day',
    itinerary: [
      { day: 1, activities: ['Arrive Ubud, Campuhan Ridge sunset walk', 'Nightly Kecak dance at Uluwatu', 'Welcome dinner at Locavore'] },
      { day: 2, activities: ['Tegallalang Rice Terraces dawn walk', 'Ubud Sacred Monkey Forest', 'Silver jewellery workshop Celuk'] },
      { day: 3, activities: ['Sunrise volcano trek on Mount Batur', 'Natural hot springs soak', 'Balinese massage afternoon'] },
      { day: 4, activities: ['Tanah Lot oceanfront temple at low tide', 'Jatiluwih cycling tour (UNESCO terraces)', 'Sunset at Pura Ulun Danu Bratan'] },
      { day: 5, activities: ['Besakih Mother Temple', 'Tirta Empul water purification ceremony', 'Mozaic Restaurant dinner'] },
      { day: 6, activities: ['Nusa Penida cliffs', 'Crystal Bay snorkelling', 'Kelingking Beach viewpoint'] },
      { day: 7, activities: ['Dawn meditation at Campuhan Ridge', 'Ubud market', 'COMO Shambhala spa afternoon'] },
      { day: 8, activities: ['Final sunrise paddy walk', 'Seminyak beach', 'Departure'] },
    ],
    places: ['Tegallalang Rice Terraces', 'Tanah Lot Temple', 'Ubud Sacred Monkey Forest', 'Besakih Mother Temple', 'Nusa Penida Cliffs'],
    restaurants: ['Locavore Ubud', 'Mozaic Restaurant', 'Swept Away at COMO Shambhala', 'Merah Putih'],
    experiences: ['Dawn Meditation at Campuhan Ridge', 'Silver Jewellery Workshop', 'Jatiluwih Cycling Tour', 'Traditional Kecak Dance', 'Sunrise Volcano Trek'],
  },
  {
    id: 'swiss-alps',
    creatorId: 'elena-kovacs',
    savedCount: 1260,
    rating: 4.7,
    name: 'Swiss Alps Winter',
    destination: 'Swiss Alps',
    region: 'Switzerland',
    duration: '6 Days',
    bestTime: 'Dec – Mar',
    overview: 'Towering peaks, crystalline alpine air, and centuries of precision craftsmanship. The Swiss Alps define the premium mountain experience in every season.',
    imageKey: 'alps',
    budget: '$$$$',
    dailyBudget: '$350–600/day',
    itinerary: [
      { day: 1, activities: ['Arrive Zurich, scenic train to Grindelwald', 'Village evening stroll', 'Fondue in a mountain hut'] },
      { day: 2, activities: ['Jungfraujoch — Top of Europe by train', 'Sphinx Observatory', 'Aletsch Glacier panorama'] },
      { day: 3, activities: ['Off-piste ski touring with guide', 'Alpine wellness spa', 'Restaurant Chesery Gstaad dinner'] },
      { day: 4, activities: ['Matterhorn Glacier Paradise (Zermatt)', 'Glacier hiking on Gorner', 'Altitude Restaurant dinner'] },
      { day: 5, activities: ['Lucerne Chapel Bridge', 'Chocolate atelier visit', 'Swiss watch workshop'] },
      { day: 6, activities: ['Final sunrise ski run', 'Il Tartufo Verbier farewell lunch', 'Departure'] },
    ],
    places: ['Jungfraujoch — Top of Europe', 'Grindelwald Village', 'Matterhorn Glacier Paradise', 'Aletsch Glacier', 'Lucerne Chapel Bridge'],
    restaurants: ['Restaurant Chesery Gstaad', 'Il Tartufo Verbier', 'Altitude Restaurant Zermatt', 'La Vache Crans-Montana'],
    experiences: ['Off-Piste Ski Touring', 'Glacier Hiking', 'Chocolate Atelier Visit', 'Alpine Wellness Spa', 'Fondue in a Mountain Hut'],
  },
  {
    id: 'monaco',
    creatorId: 'marco-vitale',
    savedCount: 1710,
    rating: 4.6,
    name: 'Monaco Grand Tour',
    destination: 'Monaco',
    region: 'French Riviera',
    duration: '4 Days',
    bestTime: 'May – Sep',
    overview: 'The Principality that redefined glamour. Every thoroughfare is a stage, from the legendary casino to the cliff-hugging Grand Prix circuit.',
    imageKey: 'yacht',
    budget: '$$$$',
    dailyBudget: '$500–900/day',
    itinerary: [
      { day: 1, activities: ['Port Hercule superyacht promenade', 'Oceanographic Museum', 'Blue Bay Monte-Carlo dinner'] },
      { day: 2, activities: ['Prince\'s Palace changing of guard', 'Old Town Rock walk', 'Casino Royale evening dress code'] },
      { day: 3, activities: ['Grand Prix circuit walk (Hairpin, Tunnel)', 'Maya Bay terrace lunch', 'Jardin Exotique succulents'] },
      { day: 4, activities: ['Perfume atelier day trip to Grasse', 'Monaco Historic Drive', 'Le Louis XV farewell dinner'] },
    ],
    places: ['Casino de Monte-Carlo', 'Prince\'s Palace & Changing of the Guard', 'Oceanographic Museum', 'Jardin Exotique', 'Old Town Rock'],
    restaurants: ['Le Louis XV – Alain Ducasse', 'Joël Robuchon Restaurant', 'Blue Bay Monte-Carlo', 'Maya Bay'],
    experiences: ['Port Hercule Yacht Walk', 'Grand Prix Circuit Walk', 'Casino Royale Evening', 'Perfume Atelier Grasse Day Trip', 'Monaco Historic Drive'],
  },
  {
    id: 'amalfi-coast',
    creatorId: 'marco-vitale',
    savedCount: 2090,
    rating: 4.8,
    name: 'Amalfi Coast Journey',
    destination: 'Amalfi Coast',
    region: 'Campania, Italy',
    duration: '6 Days',
    bestTime: 'May – Sep',
    overview: 'A UNESCO World Heritage coastline of pastel villages, lemon groves, and cerulean sea. The Amalfi Drive remains one of the world\'s most scenic roads.',
    imageKey: 'yacht',
    budget: '$$$',
    dailyBudget: '$200–350/day',
    itinerary: [
      { day: 1, activities: ['Arrive Positano, coastal walk to the village', 'Sunset Aperol at Ristorante Max terrace', 'First Amalfi Drive drive'] },
      { day: 2, activities: ['Path of the Gods hiking trail', 'Ravello Gardens', 'Don Alfonso 1890 dinner'] },
      { day: 3, activities: ['Amalfi Cathedral & town', 'Limoncello distillery visit', 'Coastal sailing day along the cliffs'] },
      { day: 4, activities: ['Emerald Grotto boat tour', 'Furore Fjord viewpoint', 'Ceramics workshop Vietri sul Mare'] },
      { day: 5, activities: ['Pompeii archaeological walk with guide', 'La Serra Ravello farewell lunch', 'Il Pirata D\'Amalfi dinner'] },
      { day: 6, activities: ['Final dawn swim at Li Galli viewpoint', 'Positano market', 'Departure'] },
    ],
    places: ['Positano Village', 'Ravello Gardens', 'Amalfi Cathedral', 'Emerald Grotto', 'Furore Fjord'],
    restaurants: ['Don Alfonso 1890', 'Ristorante Max Positano', 'La Serra Ravello', 'Il Pirata D\'Amalfi'],
    experiences: ['Path of the Gods Hiking Trail', 'Limoncello Distillery Visit', 'Coastal Sailing Day', 'Pompeii Archaeological Walk', 'Ceramics Workshop Vietri'],
  },
  {
    id: 'tokyo',
    creatorId: 'sophia-chen',
    savedCount: 4200,
    rating: 5.0,
    name: 'Tokyo Discovery',
    destination: 'Tokyo',
    region: 'Kantō, Japan',
    duration: '7 Days',
    bestTime: 'Mar – May, Sep – Nov',
    overview: 'The city that moves at the speed of the future without abandoning its ancient soul. From Michelin-star dining to serene temple gardens, Tokyo contains multitudes.',
    imageKey: 'city',
    budget: '$$$',
    dailyBudget: '$150–250/day',
    itinerary: [
      { day: 1, activities: ['Arrive, Shinjuku Gyoen twilight walk', 'Kabukicho neon stroll', 'Izakaya dinner Shinjuku'] },
      { day: 2, activities: ['Dawn Tsukiji Outer Market tuna observation', 'Senso-ji Temple Asakusa', 'Teamlab Borderless evening'] },
      { day: 3, activities: ['Traditional tea ceremony', 'Roppongi Hills art museums', 'Sukiyabashi Jiro lunch reservation'] },
      { day: 4, activities: ['Harajuku Takeshita-dori', 'Meiji Jingu forest shrine', 'Shibuya Crossing at night'] },
      { day: 5, activities: ['Woodblock print workshop', 'Akihabara electronics district', 'Ryugin Nishiazabu dinner'] },
      { day: 6, activities: ['Kabuki Theatre matinée', 'Yanaka historic neighbourhood', 'Craft sake tasting'] },
      { day: 7, activities: ['Shinjuku Imperial Garden morning', 'Final ramen pilgrimage', 'Departure from Narita'] },
    ],
    places: ['Senso-ji Temple Asakusa', 'TeamLab Borderless', 'Tsukiji Outer Market', 'Shinjuku Gyoen Garden', 'Roppongi Hills'],
    restaurants: ['Sukiyabashi Jiro Honten', 'Ryugin Nishiazabu', 'Ishikawa Kagurazaka', 'Narisawa Minami-Aoyama'],
    experiences: ['Dawn Tuna Auction Observation', 'Traditional Tea Ceremony', 'Kabuki Theatre Matinée', 'Shibuya Crossing at Night', 'Woodblock Print Workshop'],
  },
  {
    id: 'kyoto',
    creatorId: 'sophia-chen',
    savedCount: 3150,
    rating: 4.9,
    name: 'Kyoto Cultural Immersion',
    destination: 'Kyoto',
    region: 'Kansai, Japan',
    duration: '5 Days',
    bestTime: 'Mar – Apr, Oct – Nov',
    overview: 'Japan\'s ancient capital holds more UNESCO World Heritage sites than almost any city on earth. Where Zen philosophy becomes visible in garden, temple, and alley.',
    imageKey: 'temple',
    budget: '$$',
    dailyBudget: '$80–140/day',
    itinerary: [
      { day: 1, activities: ['Fushimi Inari dusk walk through vermilion gates', 'Nishiki Market', 'Gion evening lantern stroll'] },
      { day: 2, activities: ['Arashiyama Bamboo Grove at dawn', 'Monkey Park viewpoint', 'Tenryu-ji Zen garden'] },
      { day: 3, activities: ['Kinkaku-ji Golden Pavilion', 'Ryoan-ji rock garden meditation', 'Tea ceremony at Urasenke'] },
      { day: 4, activities: ['Philosopher\'s Path cherry-blossom canal walk', 'Nanzen-ji aqueduct', 'Sake brewery tour Fushimi'] },
      { day: 5, activities: ['Ikebana flower arrangement class', 'Nishiki farewell market', 'Departure'] },
    ],
    places: ['Fushimi Inari-Taisha Shrine', 'Arashiyama Bamboo Grove', 'Kinkaku-ji Golden Pavilion', 'Philosopher\'s Path', 'Nishiki Market'],
    restaurants: ['Kikunoi Honten', 'Nakamura Nakagyo', 'Mizai Gion', 'Kichisen'],
    experiences: ['Dawn Walk at Fushimi Inari', 'Matcha Ceremony at Urasenke', 'Geisha District Evening Walk', 'Ikebana Flower Arrangement', 'Kodo Incense Ceremony'],
  },
  {
    id: 'iceland',
    creatorId: 'elena-kovacs',
    savedCount: 1870,
    rating: 4.8,
    name: 'Iceland Wild',
    destination: 'Iceland',
    region: 'North Atlantic',
    duration: '7 Days',
    bestTime: 'Jun – Aug · Dec – Feb',
    overview: 'Where volcanic fire meets ancient ice. Iceland offers landscapes that challenge every expectation — geysers, glaciers, aurora borealis, and empty roads to infinity.',
    imageKey: 'mountain',
    budget: '$$$',
    dailyBudget: '$200–320/day',
    itinerary: [
      { day: 1, activities: ['Arrive Reykjavík, Blue Lagoon geothermal soak', 'Old Harbour seafood dinner', 'Aurora forecast check'] },
      { day: 2, activities: ['Golden Circle: Geysir & Gullfoss', 'Þingvellir tectonic rift walk', 'Dill Restaurant Nordic dinner'] },
      { day: 3, activities: ['Jökulsárlón Glacier Lagoon iceberg sail', 'Diamond Beach', 'Skógafoss waterfall'] },
      { day: 4, activities: ['Vatnajökull glacier hiking with crampons', 'Ice cave exploration', 'Northern lights photography'] },
      { day: 5, activities: ['Snæfellsjökull Peninsula drive', 'Kirkjufell mountain', 'Puffin colony visit'] },
      { day: 6, activities: ['Whale watching from Húsavík', 'Midnight sun walk', 'Matur og Drykkur farewell dinner'] },
      { day: 7, activities: ['Reykjavík street art tour', 'Hallgrímskirkja tower', 'Departure'] },
    ],
    places: ['Blue Lagoon Geothermal Spa', 'Gullfoss Waterfall', 'Geysir Geothermal Area', 'Skógafoss Falls', 'Jökulsárlón Glacier Lagoon'],
    restaurants: ['Dill Restaurant Reykjavík', 'Matur og Drykkur', 'Grillið Sky Restaurant', 'Fiskfélagið Fish Company'],
    experiences: ['Northern Lights Photography', 'Glacier Hiking Vatnajökull', 'Midnight Sun Walk', 'Whale Watching', 'Puffin Colony Visit'],
  },
  {
    id: 'french-riviera',
    creatorId: 'marco-vitale',
    savedCount: 2540,
    rating: 4.7,
    name: 'French Riviera',
    destination: 'Côte d\'Azur',
    region: 'Provence, France',
    duration: '6 Days',
    bestTime: 'May – Sep',
    overview: 'Sunlight over the Mediterranean, rosé on sun-bleached terraces, and the effortless glamour that only the Riviera can produce. From Nice to Antibes, every stop is iconic.',
    imageKey: 'yacht',
    budget: '$$$',
    dailyBudget: '$180–300/day',
    itinerary: [
      { day: 1, activities: ['Arrive Nice, Old Town Vieux-Nice stroll', 'Morning fish market', 'La Petite Maison dinner'] },
      { day: 2, activities: ['Cap Ferrat Peninsula walk', 'Villa Ephrussi de Rothschild gardens', 'Rosé tasting at Château Minuty'] },
      { day: 3, activities: ['Antibes Ramparts walk', 'Picasso Museum Antibes', 'Eze village medieval perch'] },
      { day: 4, activities: ['Cannes La Croisette promenade', 'Lerins Island boat excursion', 'Chèvre d\'Or dinner with panorama'] },
      { day: 5, activities: ['Lavender fields Grasse walk', 'Perfume atelier creation', 'Yacht day along the coast'] },
      { day: 6, activities: ['Scenic Grande Corniche drive', 'Monaco detour', 'Departure from Nice'] },
    ],
    places: ['Old Town Nice', 'Cap Ferrat Peninsula', 'Antibes Ramparts', 'Eze Village', 'Cannes La Croisette'],
    restaurants: ['La Petite Maison Nice', 'Chèvre d\'Or Eze', 'Le Mas Candille Mougins', 'Christian Etienne Avignon'],
    experiences: ['Yacht Day along the Coast', 'Lavender Fields Grasse Walk', 'Picasso Museum Antibes', 'Morning Fish Market Nice', 'Scenic Drive Grande Corniche'],
  },
  {
    id: 'tuscany',
    creatorId: 'marco-vitale',
    savedCount: 1980,
    rating: 4.8,
    name: 'Tuscany Harvest',
    destination: 'Tuscany',
    region: 'Central Italy',
    duration: '7 Days',
    bestTime: 'Apr – Jun, Sep – Oct',
    overview: 'Rolling hills of cypresses, Renaissance hilltowns, and the terroir that gives the world Brunello and Chianti. Tuscany is the art of living made landscape.',
    imageKey: 'villas',
    budget: '$$$',
    dailyBudget: '$150–250/day',
    itinerary: [
      { day: 1, activities: ['Arrive Florence, Piazzale Michelangelo sunset', 'Leather workshop tour', 'Buca Mario dinner'] },
      { day: 2, activities: ['Chianti Classico cycling route', 'Castello di Ama winery', 'Sunset at Podere Belvedere'] },
      { day: 3, activities: ['Siena Medieval Centre', 'Palio della Contrade context tour', 'Osteria di Passignano dinner'] },
      { day: 4, activities: ['Truffle hunting with dogs', 'San Gimignano tower town', 'Volterra Etruscan walls'] },
      { day: 5, activities: ['Val d\'Orcia cypress road drive', 'Montalcino Brunello tasting', 'Pecorino cheese production visit'] },
      { day: 6, activities: ['Il Falconiere Cortona lunch', 'Lake Trasimeno sunset', 'La Bottega del 30 farewell dinner'] },
      { day: 7, activities: ['Arezzo antique market', 'Piero della Francesca fresco walk', 'Departure'] },
    ],
    places: ['Siena Medieval Centre', 'Val d\'Orcia Valley', 'San Gimignano Towers', 'Volterra', 'Montalcino Castle'],
    restaurants: ['Osteria di Passignano', 'Buca Mario Firenze', 'La Bottega del 30', 'Il Falconiere Cortona'],
    experiences: ['Truffle Hunting with Dogs', 'Sunset at Podere Belvedere', 'Chianti Classico Cycling Route', 'Leather Workshop Firenze', 'Pecorino Cheese Tasting'],
  },
  {
    id: 'marrakech',
    creatorId: 'nadia-al-rashid',
    savedCount: 1430,
    rating: 4.7,
    name: 'Marrakech Medina',
    destination: 'Marrakech',
    region: 'Morocco',
    duration: '5 Days',
    bestTime: 'Mar – May, Oct – Nov',
    overview: 'Ochre walls, scented souks, and riads with courtyard fountains that blur the boundary between dream and reality. Marrakech engages every sense simultaneously.',
    imageKey: 'desert',
    budget: '$$',
    dailyBudget: '$60–120/day',
    itinerary: [
      { day: 1, activities: ['Arrive, riad check-in Medina', 'Djemaa el-Fna square at dusk', 'Street food tour by lamplight'] },
      { day: 2, activities: ['Jardin Majorelle morning', 'Bahia Palace', 'Hammam ritual at a traditional bathhouse'] },
      { day: 3, activities: ['Souk navigation with local guide', 'Saadian Tombs', 'Cooking class in a riad kitchen'] },
      { day: 4, activities: ['Erg Chebbi Sahara day trip', 'Camel sunrise ride', 'Berber camp dinner'] },
      { day: 5, activities: ['Atlas Mountains morning walk', 'Dar Moha farewell lunch', 'Departure'] },
    ],
    places: ['Djemaa el-Fna Square', 'Saadian Tombs', 'Bahia Palace', 'Jardin Majorelle', 'Medina Souks'],
    restaurants: ['Le Jardin Marrakech', 'Nomad Derb Aarjane', 'Dar Moha', 'La Maison Arabe'],
    experiences: ['Souk Navigation with Local Guide', 'Hammam Ritual', 'Erg Chebbi Camel Sunrise', 'Cooking Class in a Riad', 'Atlas Mountains Day Walk'],
  },
  {
    id: 'cappadocia',
    creatorId: 'nadia-al-rashid',
    savedCount: 1670,
    rating: 4.6,
    name: 'Cappadocia Sky',
    destination: 'Cappadocia',
    region: 'Anatolia, Turkey',
    duration: '4 Days',
    bestTime: 'Apr – Jun, Sep – Nov',
    overview: 'A dreamscape of volcanic rock sculpted over millennia into spires, valleys, and cave dwellings. At dawn, hundreds of hot air balloons fill the sky — one of travel\'s most transcendent sights.',
    imageKey: 'desert',
    budget: '$$',
    dailyBudget: '$70–130/day',
    itinerary: [
      { day: 1, activities: ['Arrive, cave hotel check-in', 'Göreme Open-Air Museum frescoes', 'Sunset at Rose Valley viewpoint'] },
      { day: 2, activities: ['Dawn hot air balloon flight over the valleys', 'Champagne toast on landing', 'Uçhisar Castle panorama'] },
      { day: 3, activities: ['Pottery workshop Avanos', 'Derinkuyu Underground City', 'Whirling Dervish ceremony'] },
      { day: 4, activities: ['Pigeon Valley hike', 'Cave Church fresco walk', 'Departure'] },
    ],
    places: ['Göreme Open-Air Museum', 'Uçhisar Castle', 'Rose Valley Hiking Trail', 'Derinkuyu Underground City', 'Pigeon Valley'],
    restaurants: ['Seten Restaurant', 'Dibek Göreme', 'Peri Restaurant', 'Topdeck Cave Restaurant'],
    experiences: ['Dawn Hot Air Balloon Flight', 'Cave Church Fresco Walk', 'Pottery Workshop Avanos', 'Whirling Dervish Ceremony', 'Underground City Exploration'],
  },
  {
    id: 'zanzibar',
    creatorId: 'amara-osei',
    savedCount: 1320,
    rating: 4.8,
    name: 'Zanzibar Shores',
    destination: 'Zanzibar',
    region: 'Tanzania',
    duration: '6 Days',
    bestTime: 'Jun – Oct',
    overview: 'Spice islands fringed by Indian Ocean waters of impossible turquoise. Stone Town\'s labyrinthine alleys tell centuries of Swahili, Arab, and Portuguese history.',
    imageKey: 'zanzibar',
    budget: '$',
    dailyBudget: '$40–80/day',
    itinerary: [
      { day: 1, activities: ['Arrive Zanzibar, Stone Town check-in', 'Stone Town UNESCO night walk', 'Forodhani Gardens Night Market'] },
      { day: 2, activities: ['Spice plantation tour', 'Old Fort & Slave Market history', 'Emerson Spice Rooftop dinner'] },
      { day: 3, activities: ['Nungwi Beach north coast', 'Sunset dhow sailing cruise', 'Seafood beach grill'] },
      { day: 4, activities: ['Swimming with wild dolphins', 'Mnemba Atoll snorkelling', 'The Rock Restaurant on the water'] },
      { day: 5, activities: ['Prison Island giant tortoise sanctuary', 'Blue Safari Island', 'The Swahili House dinner'] },
      { day: 6, activities: ['Final Jozani Forest colobus monkey walk', 'Stone Town market farewell', 'Departure'] },
    ],
    places: ['Stone Town UNESCO Old City', 'Jozani Chwaka Bay Forest', 'Nungwi Beach', 'Mnemba Island', 'Prison Island Tortoise Sanctuary'],
    restaurants: ['The Rock Restaurant', 'The Swahili House', 'Emerson Spice Rooftop', 'Forodhani Gardens Night Market'],
    experiences: ['Spice Plantation Tour', 'Sunset Dhow Cruise', 'Swimming with Dolphins', 'Blue Safari Island', 'Stone Town Night Walk'],
  },
  {
    id: 'singapore',
    creatorId: 'sophia-chen',
    savedCount: 2760,
    rating: 4.8,
    name: 'Singapore Edit',
    destination: 'Singapore',
    region: 'Southeast Asia',
    duration: '4 Days',
    bestTime: 'Feb – Apr',
    overview: 'An island city-state that distills the future of urban living. Immaculate parks, world-class dining, and multilayered cultural districts reward every type of explorer.',
    imageKey: 'city',
    budget: '$$$',
    dailyBudget: '$160–260/day',
    itinerary: [
      { day: 1, activities: ['Gardens by the Bay Supertrees at dusk', 'Supertree Grove light show', 'Odette National Gallery dinner'] },
      { day: 2, activities: ['Marina Bay Sands Skypark panorama', 'Chinatown Heritage Centre', 'Hawker Centre food walk Maxwell Road'] },
      { day: 3, activities: ['Botanic Gardens UNESCO morning', 'Kampong Glam Arab Quarter', 'Singapore River history walk'] },
      { day: 4, activities: ['Sentosa Island beaches', 'Night Safari evening', 'Burnt Ends farewell dinner'] },
    ],
    places: ['Gardens by the Bay Supertrees', 'Marina Bay Sands Skypark', 'Chinatown Heritage Centre', 'Kampong Glam Arab Quarter', 'Botanic Gardens UNESCO'],
    restaurants: ['Odette National Gallery', 'Les Amis Orchard', 'Burnt Ends Teck Lim', 'Zén Bukit Pasoh'],
    experiences: ['Supertree Grove Light Show', 'Hawker Centre Food Walk', 'Singapore River History Walk', 'Sentosa Island Day', 'Night Safari'],
  },
  {
    id: 'lake-como',
    creatorId: 'marco-vitale',
    savedCount: 1550,
    rating: 4.7,
    name: 'Lake Como Idyll',
    destination: 'Lake Como',
    region: 'Lombardy, Italy',
    duration: '5 Days',
    bestTime: 'Apr – Jun, Sep – Oct',
    overview: 'Lombardy\'s glacial lake has been the retreat of European nobility and artists for centuries. Villa gardens, ferry crossings, and Dolomite reflections create an atmosphere unlike anywhere else.',
    imageKey: 'lakecomo',
    budget: '$$$',
    dailyBudget: '$200–350/day',
    itinerary: [
      { day: 1, activities: ['Arrive Como town, Cathedral visit', 'Silk factory tour', 'Il Sereno lakeside dinner'] },
      { day: 2, activities: ['Bellagio village ferry crossing', 'Villa del Balbianello gardens', 'Ristorante La Punta sunset dinner'] },
      { day: 3, activities: ['Dawn kayaking on the lake', 'Varenna Old Town', 'Berton al Lago lunch'] },
      { day: 4, activities: ['Villa Carlotta Botanical Gardens', 'Hiking Monte Bregagno', 'Al Gatto Nero Cernobbio dinner'] },
      { day: 5, activities: ['Lake ferry island hopping', 'Final villa garden private tour', 'Departure to Milan'] },
    ],
    places: ['Bellagio Village', 'Villa del Balbianello Gardens', 'Varenna Old Town', 'Como Cathedral', 'Villa Carlotta Botanical Gardens'],
    restaurants: ['Ristorante La Punta Bellagio', 'Berton al Lago', 'Al Gatto Nero Cernobbio', 'Il Sereno Lago di Como'],
    experiences: ['Lake Ferry Island Hopping', 'Villa Garden Private Tour', 'Kayaking at Dawn', 'Silk Factory Visit Como Town', 'Hiking Monte Bregagno'],
  },
  {
    id: 'patagonia',
    creatorId: 'elena-kovacs',
    savedCount: 980,
    rating: 4.9,
    name: 'Patagonia Expedition',
    destination: 'Patagonia',
    region: 'Chile & Argentina',
    duration: '10 Days',
    bestTime: 'Nov – Mar',
    overview: 'The end of the world, rendered magnificent. Patagonia\'s granite towers, ancient glaciers, and wild pampas represent the last great wilderness — untouched, untamed, unforgettable.',
    imageKey: 'mountain',
    budget: '$$$',
    dailyBudget: '$180–300/day',
    itinerary: [
      { day: 1, activities: ['Arrive Puerto Natales, planning evening', 'Martin Fierro welcome dinner'] },
      { day: 2, activities: ['Torres del Paine park entry', 'Base Las Torres hike', 'Mirador viewpoint at dusk'] },
      { day: 3, activities: ['W Trek: Valle del Francés', 'Hanging glaciers viewpoint', 'Wildcamp under stars'] },
      { day: 4, activities: ['Grey Glacier boat crossing', 'Iceberg field walk', 'Refugio Paine Grande'] },
      { day: 5, activities: ['Fitz Roy Massif day hike', 'Laguna de los Tres', 'El Calafate dinner'] },
      { day: 6, activities: ['Perito Moreno Glacier walkway', 'Glacier ice walk with crampons', 'Eolo Lodge dinner'] },
      { day: 7, activities: ['Condor observation at dawn', 'Gaucho estancia day', 'Horseback riding on the pampa'] },
      { day: 8, activities: ['Puerto Natales market', 'La Mesita Grande dinner', 'Tierra del Fuego preparation'] },
      { day: 9, activities: ['Tierra del Fuego Beagle Channel cruise', 'End of the World lighthouse', 'Stargazing in the pampa'] },
      { day: 10, activities: ['Final sunrise trail', 'Departure from Punta Arenas'] },
    ],
    places: ['Torres del Paine National Park', 'Perito Moreno Glacier', 'Fitz Roy Massif', 'Puerto Natales', 'Tierra del Fuego'],
    restaurants: ['Eolo Lodge Dining Room', 'La Mesita Grande Torres del Paine', 'Martin Fierro Puerto Natales', 'El Calafate Parrilla'],
    experiences: ['W Trek Multi-Day Hike', 'Glacier Ice Walk', 'Condor Observation', 'Gaucho Estancia Day', 'Stargazing in the Pampa'],
  },
];

// ─── Seed-data note ───────────────────────────────────────────────────────────
//
// JOURNEYS above are DEMO / SEED data only.
// They populate the app while the Firestore creator_journeys collection is empty.
// Real content is uploaded by creators via the upload-journey screen and stored
// in Firestore. The service layer (lib/creatorJourneyService.ts) merges live
// Firestore journeys with this seed data at runtime.
//
// ─────────────────────────────────────────────────────────────────────────────

import type { CreatorJourney } from './creatorJourneyModel';

/**
 * Maps a hardcoded seed Journey to the canonical CreatorJourney model.
 * Used by creatorJourneyService as a fallback when Firestore has no data.
 */
export function mapSeedToCreatorJourney(j: Journey): CreatorJourney {
  return {
    id: j.id,
    creatorId: j.creatorId,
    creatorName: '',          // resolved at display time via creators.ts
    title: j.name,
    destination: j.destination,
    region: j.region,
    duration: j.duration,
    bestTime: j.bestTime,
    overview: j.overview,
    budget: j.budget,
    dailyBudget: j.dailyBudget,
    imageUri: null,
    imageKey: j.imageKey,
    places: [...j.places],
    restaurants: [...j.restaurants],
    experiences: [...j.experiences],
    itinerary: j.itinerary.map((d) => ({
      day: d.day,
      activities: [...d.activities],
    })),
    rating: j.rating,
    savedCount: j.savedCount,
    status: 'published',
    isDemo: true,
    createdAt: null,
  };
}
