import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { useEffect, useMemo, useState } from 'react';
import {
  Alert,
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { getAuth } from 'firebase/auth';
import {
  LuxuryBorderRadius,
  LuxuryColors,
  LuxuryShadow,
  LuxurySpacing,
} from '../../constants/luxuryTheme';
import {
  getCreateTripDraft,
  patchCreateTripDraft,
  type CreateTripDraft,
  type ExperienceDraft,
  type PhotoEntryDraft,
  clearCreateTripDraft,
} from '../../constants/createTripDraftStore';
import { MEMORY_GALLERY_SELECTION_KEY, sortPhotosByDate } from '../../lib/sortPhotosByDate';
import { normalizePhotoCategory as normalizeSharedPhotoCategory, normalizePhotoSource } from '../../lib/photoCategory';
import { createPublishedExperience } from '../../lib/creatorExperienceService';
import { getFirebaseApp } from '../../lib/firebase';

const CYAN = '#8AE6FF';
const STEPS = [
  { label: 'Trip Info', route: '/(tabs)/create-trip' },
  { label: 'Itinerary', route: '/(tabs)/create-trip-itinerary' },
  { label: 'Photos', route: '/(tabs)/create-trip-photos' },
  { label: 'Experience', route: '/(tabs)/create-trip-experiences' },
  { label: 'Review', route: '/(tabs)/create-trip-review' },
] as const;
const ACTIVE_STEP = 4;
const FINAL_TRIP_PAYLOAD_KEY = '@createTrip/finalPayload';
const EXPERIENCE_CATEGORIES = ['Place', 'Food', 'Activity'] as const;

type ItineraryDay = {
  id: string;
  dayLabel: string;
  dateLabel: string;
  title: string;
  subtitle: string;
  imageUri: string;
  activities: string[];
};

function normalizePhotoCategory(category: string | undefined): 'food' | 'places' | 'activities' | null {
  const normalized = normalizePhotoCategoryShared(category);
  if (normalized === 'other') return null;
  return normalized;
}

function normalizePhotoCategoryShared(category: string | undefined): 'food' | 'places' | 'activities' | 'other' {
  return normalizeSharedPhotoCategory(category);
}

function generateExperienceTitle(category: 'food' | 'places' | 'activities', index: number): string {
  if (category === 'food') {
    const options = ['Best Food', 'Local Cuisine', 'Chef Selection', 'Must Try Dish'];
    return options[index % options.length];
  }
  if (category === 'activities') {
    const options = ['Top Experience', 'Adventure Activity', 'Outdoor Experience', 'Memorable Moment'];
    return options[index % options.length];
  }
  const options = ['Top Place', 'Iconic Stop', 'Nature Viewpoint', 'Cultural Site'];
  return options[index % options.length];
}

function buildAutoExperiencesFromPhotos(photos: PhotoEntryDraft[], destination: string, startDate: string): ExperienceDraft[] {
  const seenPhotoIds = new Set<string>();
  return photos.reduce<ExperienceDraft[]>((acc, photo, index) => {
    const normalized = normalizePhotoCategory(photo.category);
    if (!normalized) return acc;
    const sourcePhotoId = (photo.id ?? '').trim();
    if (!sourcePhotoId || seenPhotoIds.has(sourcePhotoId)) return acc;

    const location = destination.trim() || 'Location TBD';
    const dateDay = startDate.trim() || 'Day TBD';

    acc.push({
      id: `auto-${sourcePhotoId}`,
      title: generateExperienceTitle(normalized, index),
      category: normalized === 'food' ? 'Food' : normalized === 'activities' ? 'Activity' : 'Place',
      sourcePhotoId,
      aiGenerated: true,
      rating: 4.8,
      imageUri: photo.uri,
      location,
      dateDay,
      locationDate: `${location} - ${dateDay}`,
      notes: `Auto-generated from ${normalized} photo classification.`,
    });
    seenPhotoIds.add(sourcePhotoId);
    return acc;
  }, []);
}

function mergeExperiences(autoGenerated: ExperienceDraft[], manual: ExperienceDraft[]): ExperienceDraft[] {
  const result: ExperienceDraft[] = [];
  const seenPhoto = new Set<string>();
  const seenId = new Set<string>();

  for (const exp of autoGenerated) {
    const sourcePhotoId = (exp.sourcePhotoId ?? '').trim();
    if (!sourcePhotoId || seenPhoto.has(sourcePhotoId)) continue;
    result.push(exp);
    seenPhoto.add(sourcePhotoId);
    seenId.add(exp.id);
  }

  for (const exp of manual) {
    const id = (exp.id ?? '').trim();
    if (id && seenId.has(id)) continue;
    result.push(exp);
    if (id) seenId.add(id);
  }

  return result;
}

function parseTripDateInput(value: string): Date | null {
  const raw = value.trim();
  if (!raw) return null;

  const parsed = new Date(raw);
  if (!Number.isNaN(parsed.getTime())) return parsed;

  const dayMonth = raw.match(/^(\d{1,2})\s+([A-Za-z]{3,})(?:\s+(\d{4}))?$/);
  if (dayMonth) {
    const day = Number(dayMonth[1]);
    const monthKey = dayMonth[2].slice(0, 3).toLowerCase();
    const monthLookup: Record<string, number> = {
      jan: 0,
      feb: 1,
      mar: 2,
      apr: 3,
      may: 4,
      jun: 5,
      jul: 6,
      aug: 7,
      sep: 8,
      oct: 9,
      nov: 10,
      dec: 11,
    };
    const month = monthLookup[monthKey];
    const year = dayMonth[3] ? Number(dayMonth[3]) : 2000;
    if (month !== undefined) {
      const built = new Date(year, month, day);
      if (!Number.isNaN(built.getTime())) return built;
    }
  }

  const dmy = raw.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);
  if (dmy) {
    const day = Number(dmy[1]);
    const month = Number(dmy[2]) - 1;
    const year = Number(dmy[3].length === 2 ? `20${dmy[3]}` : dmy[3]);
    const built = new Date(year, month, day);
    if (!Number.isNaN(built.getTime())) return built;
  }

  return null;
}

function buildTripDateRange(startDate: string, endDate: string): Date[] {
  const start = parseTripDateInput(startDate);
  const end = parseTripDateInput(endDate || startDate);
  if (!start || !end) return [];

  const startOnly = new Date(start.getFullYear(), start.getMonth(), start.getDate());
  const endOnly = new Date(end.getFullYear(), end.getMonth(), end.getDate());
  const low = startOnly.getTime() <= endOnly.getTime() ? startOnly : endOnly;
  const high = startOnly.getTime() <= endOnly.getTime() ? endOnly : startOnly;

  const dates: Date[] = [];
  const cursor = new Date(low);
  while (cursor.getTime() <= high.getTime()) {
    dates.push(new Date(cursor));
    cursor.setDate(cursor.getDate() + 1);
  }

  return dates;
}

function formatDateDay(date: Date): string {
  return date.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
  });
}

function generateTripTitleFromDestination(destination: string, startDate: string, endDate: string): string {
  const cleanedDestination = destination
    .replace(/,/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  if (cleanedDestination) {
    return `${cleanedDestination} Adventure`;
  }

  const cleanedStart = startDate.trim();
  const cleanedEnd = endDate.trim();
  if (cleanedStart && cleanedEnd) {
    return `Adventure ${cleanedStart} - ${cleanedEnd}`;
  }
  if (cleanedStart) {
    return `Adventure ${cleanedStart}`;
  }

  return 'My Adventure';
}

function Stepper() {
  return (
    <View style={styles.stepperWrap}>
      {STEPS.map((step, index) => {
        const active = index === ACTIVE_STEP;
        const done = index < ACTIVE_STEP;
        return (
          <React.Fragment key={step.label}>
            <TouchableOpacity style={styles.stepCol} onPress={() => router.replace(step.route)} activeOpacity={0.82}>
              <View style={[styles.stepDot, active && styles.stepDotActive, done && styles.stepDotDone]}>
                {done ? (
                  <Ionicons name="checkmark" size={9} color={LuxuryColors.success} />
                ) : (
                  <Text style={[styles.stepDotText, active && styles.stepDotTextActive]}>{index + 1}</Text>
                )}
              </View>
              <Text numberOfLines={1} ellipsizeMode="clip" style={[styles.stepText, active && styles.stepTextActive]}>{step.label}</Text>
            </TouchableOpacity>
            {index < STEPS.length - 1 ? <View style={styles.stepLine} /> : null}
          </React.Fragment>
        );
      })}
    </View>
  );
}
export default function CreateTripReviewScreen() {
  const insets = useSafeAreaInsets();
  const [submitting, setSubmitting] = useState(false);
  const [itineraryRows, setItineraryRows] = useState<ItineraryDay[]>([]);
  const [draft, setDraft] = useState<CreateTripDraft | null>(null);
  const [expandedExperienceCategory, setExpandedExperienceCategory] = useState<string | null>(null);

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const nextDraft = await getCreateTripDraft();
        if (!alive) return;
        setDraft(nextDraft);
        if (Array.isArray(nextDraft.itineraryDays)) {
          setItineraryRows(nextDraft.itineraryDays);
        }
      } catch {
        // Keep fallback preview values when no saved itinerary draft exists.
      }
    })();

    return () => {
      alive = false;
    };
  }, []);

  const tripInfo = draft?.tripInfo;
  const photos = draft?.photos ?? [];
  const sortedPhotos = useMemo(() => sortPhotosByDate(photos), [photos]);
  const autoGeneratedExperiences = useMemo(
    () => buildAutoExperiencesFromPhotos(
      sortedPhotos,
      tripInfo?.destination ?? '',
      tripInfo?.startDate ?? '',
    ),
    [sortedPhotos, tripInfo?.destination, tripInfo?.startDate],
  );
  const mergedExperiences = useMemo(
    () => mergeExperiences(autoGeneratedExperiences, draft?.experiences ?? []),
    [autoGeneratedExperiences, draft?.experiences],
  );
  const allExperiences = useMemo(() => {
    const currentDestination = (tripInfo?.destination ?? '').replace(/,/g, ' ').replace(/\s+/g, ' ').trim() || 'Location TBD';
    const tripDates = buildTripDateRange(tripInfo?.startDate ?? '', tripInfo?.endDate ?? '');
    if (tripDates.length === 0) {
      return mergedExperiences.map((exp) => ({
        ...exp,
        location: currentDestination,
      }));
    }

    return mergedExperiences.map((exp, index) => {
      const assignedDate = tripDates[index % tripDates.length];
      const dateDay = formatDateDay(assignedDate);
      return {
        ...exp,
        location: currentDestination,
        dateDay,
        locationDate: `${currentDestination} - ${dateDay}`,
      };
    });
  }, [mergedExperiences, tripInfo?.destination, tripInfo?.startDate, tripInfo?.endDate]);

  const experienceCategories = useMemo(() => {
    const shouldExcludeFromReview = (exp: (typeof allExperiences)[number]): boolean => {
      const title = (exp.title ?? '').trim().toLowerCase();
      const searchable = [
        exp.title,
        exp.location,
        exp.locationDate,
        exp.notes,
        exp.imageUri,
      ].join(' ').toLowerCase();

      if (title === 'experience') return true;
      if (searchable.includes('capri')) return true;
      if (searchable.includes('italy')) return true;
      if (searchable.includes('sunset catamaran cruise')) return true;
      if (searchable.includes('beach') || searchable.includes('sunset')) return true;

      return false;
    };

    const grouped = allExperiences.reduce<Record<string, typeof allExperiences>>((acc, exp) => {
      const category = exp.category?.trim() || 'Experience';
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(exp);
      return acc;
    }, {});

    return EXPERIENCE_CATEGORIES.map((category) => {
      const sourceItems = grouped[category] ?? [];
      const visibleItems = sourceItems.filter((item) => !shouldExcludeFromReview(item));
      const uniqueByTitle = new Map<string, (typeof allExperiences)[number]>();

      for (const item of visibleItems) {
        const key = (item.title ?? '').trim().toLowerCase();
        if (!key || uniqueByTitle.has(key)) continue;
        uniqueByTitle.set(key, item);
      }

      const items = Array.from(uniqueByTitle.values());
      return {
        category,
        items,
        thumbnail: items.find((item) => item.imageUri?.trim())?.imageUri || '',
      };
    });
  }, [allExperiences]);

  const placePhotos = useMemo(() => sortedPhotos.filter((p) => normalizePhotoCategory(p.category) === 'places'), [sortedPhotos]);
  const foodPhotos = useMemo(() => sortedPhotos.filter((p) => normalizePhotoCategory(p.category) === 'food'), [sortedPhotos]);
  const activityPhotos = useMemo(() => sortedPhotos.filter((p) => normalizePhotoCategory(p.category) === 'activities'), [sortedPhotos]);

  useEffect(() => {
    console.log('[PHOTO_COUNTED]', {
      all: sortedPhotos.length,
      places: placePhotos.length,
      food: foodPhotos.length,
      activities: activityPhotos.length,
      other: sortedPhotos.filter((p) => normalizePhotoCategoryShared(p.category) === 'other').length,
      screen: 'create-trip-review',
    });
  }, [sortedPhotos, placePhotos.length, foodPhotos.length, activityPhotos.length]);

  const itineraryPreview = useMemo(() => {
    return itineraryRows.slice(0, 3).map((day, index) => ({
      id: day.id,
      day: day.dayLabel || `Day ${index + 1}`,
      title: day.title || 'Untitled Day',
      mainActivity: day.activities.find((a) => a.trim().length > 0) || day.subtitle || 'No activities yet',
      thumbnail: day.imageUri?.trim() || sortedPhotos[index]?.uri || tripInfo?.coverUri || '',
    }));
  }, [itineraryRows, sortedPhotos, tripInfo?.coverUri]);

  const memoryGallery = useMemo(() => sortedPhotos.slice(0, 6), [sortedPhotos]);
  const extraGalleryCount = Math.max(sortedPhotos.length - 6, 0);

  const openMemoryGallery = async () => {
    try {
      await AsyncStorage.setItem(MEMORY_GALLERY_SELECTION_KEY, JSON.stringify(sortedPhotos));
    } catch {
      // Keep navigation resilient even if temp gallery transfer fails.
    }

    router.push('/memory-gallery');
  };

  const heroImage = tripInfo?.coverUri || sortedPhotos[0]?.uri || itineraryRows[0]?.imageUri || '';
  const dateRange = [tripInfo?.startDate, tripInfo?.endDate].filter(Boolean).join(' - ');

  const mapBudgetToRange = (budgetRaw: string): '$' | '$$' | '$$$' | '$$$$' => {
    const n = Number.parseInt(budgetRaw, 10);
    if (!Number.isFinite(n)) return '$$';
    if (n < 1200) return '$';
    if (n < 3000) return '$$';
    if (n < 7000) return '$$$';
    return '$$$$';
  };

  const mapTripTypeToStyle = (tripType: string): 'luxury' | 'adventure' | 'budget' | 'family' | 'food' => {
    const normalized = tripType.toLowerCase();
    if (normalized.includes('adventure')) return 'adventure';
    if (normalized.includes('family')) return 'family';
    if (normalized.includes('food')) return 'food';
    if (normalized.includes('budget')) return 'budget';
    return 'luxury';
  };

  const validateDraftForPublish = (currentDraft: CreateTripDraft): string[] => {
    const issues: string[] = [];
    const info = currentDraft.tripInfo;

    if (!info.destination.trim()) issues.push('Destination is required.');
    if (!info.startDate.trim()) issues.push('Start Date is required.');
    if (!info.endDate.trim()) issues.push('End Date is required.');
    if (!info.travelers.trim()) issues.push('Travelers is required.');
    if (currentDraft.itineraryDays.length === 0) issues.push('Add at least one itinerary day.');

    return issues;
  };

  const handleCreate = async () => {
    setSubmitting(true);
    try {
      const auth = getAuth(getFirebaseApp());
      const user = auth.currentUser;
      if (!user) {
        throw new Error('Please sign in to create a trip.');
      }

      let latestDraft = draft ?? (await getCreateTripDraft());
      const validationIssues = validateDraftForPublish(latestDraft);
      if (validationIssues.length > 0) {
        setSubmitting(false);
        Alert.alert('Missing Required Details', validationIssues.join('\n'));
        return;
      }

      let info = latestDraft.tripInfo;
      if (!info.tripTitle.trim()) {
        const generatedTripTitle = generateTripTitleFromDestination(info.destination, info.startDate, info.endDate);
        info = {
          ...info,
          tripTitle: generatedTripTitle,
        };
        latestDraft = {
          ...latestDraft,
          tripInfo: info,
        };
        setDraft(latestDraft);
        try {
          await patchCreateTripDraft({ tripInfo: info });
        } catch {
          // Continue with in-memory generated title even if persistence fails.
        }
      }

      const destination = info.destination || 'Unknown destination';
      const city = destination.split(',')[0]?.trim() || destination;
      const country = destination.split(',').slice(1).join(',').trim() || city;
      const itinerary = latestDraft.itineraryDays;
      const experiences = mergeExperiences(
        buildAutoExperiencesFromPhotos(
          latestDraft.photos,
          latestDraft.tripInfo.destination,
          latestDraft.tripInfo.startDate,
        ),
        latestDraft.experiences,
      );
      const photoUris = [
        ...(info.coverUri ? [info.coverUri] : []),
        ...info.galleryUris,
        ...latestDraft.photos.map((p) => p.uri),
        ...itinerary.map((d) => d.imageUri).filter(Boolean),
      ].filter((uri, index, arr) => Boolean(uri) && arr.indexOf(uri) === index);

      const primaryCover = itinerary.find((d) => d.imageUri?.trim())?.imageUri
        || info.coverUri
        || photoUris[0]
        || null;

      const highlights = [
        ...info.highlights,
        ...experiences.map((e) => e.title),
      ].filter(Boolean).slice(0, 8);

      const dailyPlan = itinerary.map((day, index) => ({
        day: index + 1,
        title: day.title || day.dayLabel || `Day ${index + 1}`,
        description: day.activities.filter((a) => a.trim().length > 0).join(', ') || day.subtitle || 'No activities yet',
      }));

      const normalizedTripPhotos = latestDraft.photos.map((photo) => {
        const category = normalizePhotoCategoryShared(photo.category);
        const categorySource = normalizePhotoSource(photo.categorySource ?? photo.source, category);
        const classificationStatus =
          photo.classificationStatus === 'pending' || photo.classificationStatus === 'done' || photo.classificationStatus === 'failed'
            ? photo.classificationStatus
            : categorySource === 'ai'
              ? 'done'
              : 'pending';

        return {
          ...photo,
          category,
          categorySource,
          source: categorySource,
          classificationStatus,
          classificationReason: photo.classificationReason ?? '',
        };
      });

      console.log('[PHOTO_PERSISTED]', {
        screen: 'create-trip-review',
        count: normalizedTripPhotos.length,
        places: normalizedTripPhotos.filter((p) => p.category === 'places').length,
        food: normalizedTripPhotos.filter((p) => p.category === 'food').length,
        activities: normalizedTripPhotos.filter((p) => p.category === 'activities').length,
        other: normalizedTripPhotos.filter((p) => p.category === 'other').length,
      });

      const tripData = {
        version: 1,
        tripInfo: info,
        itineraryDays: itinerary,
        photos: normalizedTripPhotos,
        galleryUris: info.galleryUris,
        coverUri: info.coverUri,
        experiences,
        activities: itinerary.flatMap((day) => day.activities),
        notes: info.notes,
        highlights: info.highlights,
        travelers: info.travelers,
        dates: {
          startDate: info.startDate,
          endDate: info.endDate,
          duration: info.duration,
        },
        budget: {
          total: info.budget,
          flights: info.flightCost,
          stays: info.stayCost,
          food: info.foodCost,
          activities: info.activitiesCost,
        },
      };

      const createdId = await createPublishedExperience({
        creatorId: user.uid,
        creatorType: 'community',
        creatorName: user.displayName ?? 'Traveler',
        title: info.tripTitle || 'Untitled Trip',
        country,
        city,
        travelStyle: mapTripTypeToStyle(info.tripType),
        duration: info.duration || 'Custom',
        budget: mapBudgetToRange(info.budget),
        coverImage: primaryCover,
        description: info.notes || 'Trip created from the premium planner flow.',
        whoIsItFor: `${info.travelers || '1'} traveler(s)`,
        highlights,
        creatorNotes: info.notes || '',
        tips: itinerary.flatMap((day) => day.activities).filter((a) => a.trim().length > 0).slice(0, 8),
        bestTimeToVisit: `${info.startDate} - ${info.endDate}`,
        warnings: '',
        hiddenGems: itinerary.slice(0, 6).map((day) => ({
          name: day.title || day.dayLabel,
          description: day.subtitle || 'Saved from itinerary',
        })),
        restaurants: [],
        hotels: [],
        dailyPlan,
        googleMapsUrl: '',
        appleMapsUrl: '',
        freePreview: true,
        published: true,
        tripData,
      });

      const payload = {
        createdAt: new Date().toISOString(),
        id: createdId,
        itinerary,
        photoUris,
        experiences,
      };
      await AsyncStorage.setItem(FINAL_TRIP_PAYLOAD_KEY, JSON.stringify(payload));
      await clearCreateTripDraft();
    } catch {
      // Ignore storage errors so user flow can continue.
      setSubmitting(false);
      Alert.alert('Create Trip Failed', 'Unable to create your trip right now. Please try again.');
      return;
    }

    setTimeout(() => {
      setSubmitting(false);
      router.replace('/(tabs)/create-trip-success');
    }, 900);
  };

  return (
    <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <LinearGradient colors={['#071120', '#091A2A', '#06101D']} style={StyleSheet.absoluteFill} />

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.content, { paddingTop: insets.top + 10, paddingBottom: insets.bottom + 152 }]}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.headerRow}>
          <TouchableOpacity style={styles.circleBtn} onPress={() => router.replace('/(tabs)/create-trip-experiences')} activeOpacity={0.84}>
            <Ionicons name="arrow-back" size={19} color={LuxuryColors.textPrimary} />
          </TouchableOpacity>
          <View style={styles.headerCenter}>
            <Text style={styles.headerTitle}>Review</Text>
            <Text style={styles.headerSub}>Step 5 of 5 - Final preview</Text>
          </View>
          <Pressable style={styles.draftBtn} onPress={() => Alert.alert('Draft Saved', 'Trip draft saved.')}>
            <Text style={styles.draftText}>Save Draft</Text>
          </Pressable>
        </View>

        <Stepper />

        {/* SECTION 1 — TRIP HERO */}
        <View style={styles.heroWrap}>
          {heroImage ? <Image source={{ uri: heroImage }} style={styles.heroImage} resizeMode="cover" /> : null}
          <LinearGradient colors={['rgba(7,17,32,0.06)', 'rgba(7,17,32,0.36)', 'rgba(7,17,32,0.95)']} style={styles.heroShade} />
          <View style={styles.heroTextWrap}>
            <Text style={styles.heroTitle}>{tripInfo?.tripTitle || 'Untitled Trip'}</Text>
            <Text style={styles.heroMeta}>{tripInfo?.destination || 'Destination TBD'}</Text>
            {dateRange ? <Text style={styles.heroMeta}>{dateRange}</Text> : null}
            <View style={styles.heroChipRow}>
              <Text style={styles.heroChip}>{tripInfo?.duration || 'Duration TBD'}</Text>
              <Text style={styles.heroChip}>{tripInfo?.travelers ? `${tripInfo.travelers} Travelers` : 'Travelers TBD'}</Text>
              <Text style={styles.heroChip}>{tripInfo?.tripType || 'Trip Type'}</Text>
            </View>
          </View>
        </View>

        {/* SECTION 2 — QUICK STATS */}
        <View style={styles.statsRow}>
          <View style={styles.statPill}>
            <Ionicons name="camera-outline" size={18} color={CYAN} />
            <Text style={styles.statValue}>{photos.length}</Text>
            <Text style={styles.statLabel}>Total Photos</Text>
          </View>
          <View style={styles.statPill}>
            <Ionicons name="location-outline" size={18} color={CYAN} />
            <Text style={styles.statValue}>{placePhotos.length}</Text>
            <Text style={styles.statLabel}>Places</Text>
          </View>
          <View style={styles.statPill}>
            <Ionicons name="sparkles-outline" size={18} color={CYAN} />
            <Text style={styles.statValue}>{allExperiences.length}</Text>
            <Text style={styles.statLabel}>Experiences</Text>
          </View>
          <View style={styles.statPill}>
            <Ionicons name="calendar-outline" size={18} color={CYAN} />
            <Text style={styles.statValue}>{itineraryRows.length}</Text>
            <Text style={styles.statLabel}>Itinerary Days</Text>
          </View>
        </View>

        {/* SECTION 3 — ITINERARY SUMMARY */}
        <View style={styles.card}>
          <View style={styles.sectionTitleRow}>
            <Text style={styles.cardTitle}>Itinerary Summary</Text>
            <TouchableOpacity onPress={() => router.push('/(tabs)/create-trip-itinerary')} activeOpacity={0.85}>
              <Text style={styles.sectionLink}>View All Days</Text>
            </TouchableOpacity>
          </View>
          <View style={styles.itineraryList}>
            {itineraryPreview.map((item) => (
              <View key={item.id} style={styles.itineraryCard}>
                {item.thumbnail ? <Image source={{ uri: item.thumbnail }} style={styles.itineraryThumb} resizeMode="cover" /> : null}
                <View style={styles.itineraryText}>
                  <View style={styles.dayBadge}><Text style={styles.dayBadgeText}>{item.day}</Text></View>
                  <Text style={styles.itineraryTitle}>{item.title}</Text>
                  <Text style={styles.itineraryDetail}>{item.mainActivity}</Text>
                </View>
              </View>
            ))}
            {itineraryPreview.length === 0 ? <Text style={styles.mutedText}>No itinerary days yet.</Text> : null}
          </View>
        </View>

        {/* SECTION 4 — PHOTO HIGHLIGHTS */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Photo Highlights</Text>
          <View style={styles.highlightRow}>
            <View style={styles.highlightCard}>
              {placePhotos[0]?.uri ? <Image source={{ uri: placePhotos[0].uri }} style={styles.highlightImg} resizeMode="cover" /> : <View style={styles.highlightImgPlaceholder} />}
              <Text style={styles.highlightTitle}>Top Place</Text>
            </View>
            <View style={styles.highlightCard}>
              {foodPhotos[0]?.uri ? <Image source={{ uri: foodPhotos[0].uri }} style={styles.highlightImg} resizeMode="cover" /> : <View style={styles.highlightImgPlaceholder} />}
              <Text style={styles.highlightTitle}>Best Food</Text>
            </View>
            <View style={styles.highlightCard}>
              {activityPhotos[0]?.uri ? <Image source={{ uri: activityPhotos[0].uri }} style={styles.highlightImg} resizeMode="cover" /> : <View style={styles.highlightImgPlaceholder} />}
              <Text style={styles.highlightTitle}>Top Experience</Text>
            </View>
          </View>
        </View>

        {/* SECTION 5 - EXPERIENCES SUMMARY */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Experiences Summary</Text>

          <View style={styles.expList}>
            {experienceCategories.map(({ category, items, thumbnail }) => {
              const isExpanded = expandedExperienceCategory === category;
              return (
                <View key={category} style={styles.expAccordionCard}>
                  <TouchableOpacity
                    style={styles.expRow}
                    activeOpacity={0.85}
                    onPress={() => setExpandedExperienceCategory(isExpanded ? null : category)}
                  >
                    {thumbnail ? (
                      <Image source={{ uri: thumbnail }} style={styles.expThumb} resizeMode="cover" />
                    ) : (
                      <View style={styles.expThumbPlaceholder}>
                        <Ionicons name="image-outline" size={14} color={LuxuryColors.textSecondary} />
                      </View>
                    )}

                    <View style={styles.expTextBlock}>
                      <Text numberOfLines={1} style={styles.expTitle}>{category}</Text>
                      <Text style={styles.expMeta}>{items.length} item{items.length === 1 ? '' : 's'}</Text>
                    </View>

                    <Ionicons
                      name={isExpanded ? 'chevron-up' : 'chevron-down'}
                      size={16}
                      color={LuxuryColors.textSecondary}
                    />
                  </TouchableOpacity>

                  {isExpanded ? (
                    <View style={styles.expDetailsList}>
                      {items.map((item) => (
                        <View key={item.id} style={styles.expDetailRow}>
                          {item.imageUri ? (
                            <Image source={{ uri: item.imageUri }} style={styles.expDetailThumb} resizeMode="cover" />
                          ) : null}
                          <Text numberOfLines={1} style={styles.expDetailTitle}>{item.title || 'Untitled Experience'}</Text>
                        </View>
                      ))}
                    </View>
                  ) : null}
                </View>
              );
            })}
          </View>

          {allExperiences.length === 0 ? (
            <Text style={styles.mutedText}>No experiences yet.</Text>
          ) : null}
        </View>
              

        {/* SECTION 6 — MEMORY GALLERY */}
        <View style={styles.card}>
          <TouchableOpacity style={styles.sectionTitleRow} onPress={() => { void openMemoryGallery(); }} activeOpacity={0.84}>
            <Text style={styles.cardTitle}>Memory Gallery</Text>
            <Text style={styles.sectionLink}>Open Gallery</Text>
          </TouchableOpacity>
          <View style={styles.galleryGrid}>
            {memoryGallery.map((photo, index) => {
              const isLastVisible = index === 5 && extraGalleryCount > 0;
              return (
                <TouchableOpacity key={photo.id || `${photo.uri}-${index}`} style={styles.galleryTile} onPress={() => { void openMemoryGallery(); }} activeOpacity={0.84}>
                  <Image source={{ uri: photo.uri }} style={styles.galleryImg} resizeMode="cover" />
                  {isLastVisible ? (
                    <View style={styles.galleryOverlay}>
                      <Text style={styles.galleryOverlayText}>+{extraGalleryCount}</Text>
                    </View>
                  ) : null}
                </TouchableOpacity>
              );
            })}
          </View>
          {memoryGallery.length === 0 ? <Text style={styles.mutedText}>No photos uploaded yet.</Text> : null}
        </View>

        {/* SECTION 7 — TRIP NOTES */}
        {tripInfo?.notes?.trim() ? (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Trip Notes</Text>
            <View style={styles.notesCard}>
              <Text style={styles.notesText}>{tripInfo.notes.trim()}</Text>
            </View>
          </View>
        ) : null}

        {/* SECTION 8 — FINAL ACTIONS */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Final Actions</Text>
          <View style={styles.actionsRow}>
            <TouchableOpacity style={styles.secondaryActionBtn} onPress={handleCreate} activeOpacity={0.88}>
              <Text style={styles.secondaryActionText}>Save Trip</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.secondaryActionBtn} onPress={() => router.replace('/(tabs)/create-trip')} activeOpacity={0.88}>
              <Text style={styles.secondaryActionText}>Edit Trip</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>

      <View style={[styles.dock, { paddingBottom: 4 }]}> 
        <TouchableOpacity style={[styles.cta, submitting && { opacity: 0.7 }]} onPress={handleCreate} disabled={submitting} activeOpacity={0.88}>
          <Ionicons name={submitting ? 'hourglass-outline' : 'checkmark-circle-outline'} size={18} color={LuxuryColors.background} />
          <Text style={styles.ctaText}>{submitting ? 'Creating Trip...' : 'Create Trip'}</Text>
        </TouchableOpacity>
      </View>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: LuxuryColors.background },
  scroll: { flex: 1 },
  content: { paddingHorizontal: LuxurySpacing.lg, gap: 12 },

  headerRow: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', position: 'relative' },
  headerCenter: { position: 'absolute', left: 0, right: 0, alignItems: 'center', pointerEvents: 'none' },
  headerTitle: { color: LuxuryColors.textPrimary, fontSize: 18, fontWeight: '700' },
  headerSub: { color: LuxuryColors.textSecondary, fontSize: 11, marginTop: 2 },
  circleBtn: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(138,230,255,0.16)' },
  draftBtn: { minHeight: 36, paddingHorizontal: 12, borderRadius: LuxuryBorderRadius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(138,230,255,0.10)', borderWidth: 1, borderColor: 'rgba(138,230,255,0.26)' },
  draftText: { color: CYAN, fontSize: 12, fontWeight: '700' },

  stepperWrap: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 6, paddingVertical: 3, marginTop: -4, borderRadius: LuxuryBorderRadius.xl, backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1, borderColor: 'rgba(138,230,255,0.15)', ...LuxuryShadow.soft },
  stepCol: { flex: 1, alignItems: 'center', gap: 2 },
  stepDot: { width: 20, height: 20, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.04)' },
  stepDotActive: { backgroundColor: 'rgba(138,230,255,0.20)', borderColor: CYAN },
  stepDotDone: { backgroundColor: 'rgba(46,213,115,0.16)', borderColor: 'rgba(46,213,115,0.44)' },
  stepDotText: { color: LuxuryColors.textSecondary, fontSize: 9, fontWeight: '700', textAlign: 'center', lineHeight: 10 },
  stepDotTextActive: { color: CYAN },
  stepText: { color: LuxuryColors.textTertiary, fontSize: 7.5, fontWeight: '600', textAlign: 'center', lineHeight: 9, flexWrap: 'nowrap' },
  stepTextActive: { color: LuxuryColors.textPrimary },
  stepLine: { width: 10, flexShrink: 0, height: StyleSheet.hairlineWidth, backgroundColor: 'rgba(138,230,255,0.18)', marginHorizontal: 1 },

  heroWrap: {
    height: 230,
    borderRadius: LuxuryBorderRadius.xxl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(138,230,255,0.16)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    ...LuxuryShadow.soft,
  },
  heroImage: { width: '100%', height: '100%' },
  heroShade: { ...StyleSheet.absoluteFillObject },
  heroTextWrap: { position: 'absolute', left: 14, right: 14, bottom: 14 },
  heroTitle: { color: LuxuryColors.textPrimary, fontSize: 22, fontWeight: '800' },
  heroMeta: { color: LuxuryColors.textSecondary, fontSize: 12, marginTop: 2 },
  heroChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  heroChip: {
    color: CYAN,
    fontSize: 10,
    borderWidth: 1,
    borderColor: 'rgba(138,230,255,0.30)',
    backgroundColor: 'rgba(138,230,255,0.10)',
    borderRadius: LuxuryBorderRadius.full,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },

  statsRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  statPill: {
    width: '48.5%',
    minHeight: 76,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingVertical: 10,
  },
  statValue: { color: LuxuryColors.textPrimary, fontSize: 18, fontWeight: '800' },
  statLabel: { color: LuxuryColors.textSecondary, fontSize: 10, fontWeight: '600' },

  card: {
    borderRadius: LuxuryBorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(138,230,255,0.14)',
    padding: 12,
    gap: 10,
    ...LuxuryShadow.soft,
  },
  cardTitle: { color: LuxuryColors.textPrimary, fontSize: 14, fontWeight: '700' },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionLink: { color: CYAN, fontSize: 11, fontWeight: '700' },
  mutedText: { color: LuxuryColors.textSecondary, fontSize: 11 },

  itineraryList: { gap: 8 },
  itineraryCard: {
    minHeight: 74,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(7,17,32,0.72)',
    paddingHorizontal: 8,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  itineraryThumb: {
    width: 58,
    height: 58,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  dayBadge: {
    alignSelf: 'flex-start',
    minWidth: 50,
    minHeight: 22,
    borderRadius: LuxuryBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(138,230,255,0.36)',
    backgroundColor: 'rgba(138,230,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  dayBadgeText: { color: CYAN, fontSize: 11, fontWeight: '700' },
  itineraryText: { flex: 1 },
  itineraryTitle: { color: LuxuryColors.textPrimary, fontSize: 13, fontWeight: '700' },
  itineraryDetail: { color: LuxuryColors.textSecondary, fontSize: 11, marginTop: 2 },

  highlightRow: { flexDirection: 'row', gap: 8 },
  highlightCard: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(7,17,32,0.72)',
    padding: 8,
    gap: 6,
  },
  highlightImg: {
    width: '100%',
    height: 82,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  highlightImgPlaceholder: { width: '100%', height: 82, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.04)' },
  highlightTitle: { color: LuxuryColors.textPrimary, fontSize: 11, fontWeight: '700', textAlign: 'center' },

  expList: { gap: 8 },
  expAccordionCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(7,17,32,0.72)',
    overflow: 'hidden',
  },
  expRow: {
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  expTextBlock: { flex: 1 },
  expThumb: {
    width: 42,
    height: 42,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  expThumbPlaceholder: {
    width: 42,
    height: 42,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  expTitle: { color: LuxuryColors.textPrimary, fontSize: 13, fontWeight: '700' },
  expMeta: { color: LuxuryColors.textSecondary, fontSize: 11, marginTop: 2 },
  expDetailsList: {
    paddingHorizontal: 10,
    paddingBottom: 6,
    gap: 5,
  },
  expDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(255,255,255,0.03)',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  expDetailThumb: {
    width: 28,
    height: 28,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  expDetailTitle: { color: LuxuryColors.textPrimary, fontSize: 12, fontWeight: '600' },

  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  galleryTile: {
    width: '31.7%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    position: 'relative',
  },
  galleryImg: { width: '100%', height: '100%' },
  galleryOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7,17,32,0.66)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryOverlayText: { color: '#FFFFFF', fontWeight: '800', fontSize: 18 },

  notesCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(138,230,255,0.18)',
    backgroundColor: 'rgba(138,230,255,0.08)',
    padding: 10,
  },
  notesText: { color: LuxuryColors.textPrimary, fontSize: 12, lineHeight: 18 },

  actionsRow: { flexDirection: 'row', gap: 10 },
  secondaryActionBtn: {
    flex: 1,
    minHeight: 42,
    borderRadius: LuxuryBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(138,230,255,0.36)',
    backgroundColor: 'rgba(138,230,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionText: { color: CYAN, fontSize: 12, fontWeight: '700' },

  dock: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: LuxurySpacing.lg, paddingTop: 2, backgroundColor: 'rgba(7,17,32,0.95)', borderTopWidth: 1, borderTopColor: 'rgba(138,230,255,0.14)' },
  cta: { minHeight: 52, borderRadius: LuxuryBorderRadius.full, backgroundColor: CYAN, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, ...LuxuryShadow.gold },
  ctaText: { color: LuxuryColors.background, fontSize: 14, fontWeight: '800' },
});
